### ISSUE TITLE
Allow to override toJSONSchemaOptions

### ISSUE THREAD

**Issue by oskar-rosen-ui** [qlaffont/fastify-type-provider-valibot#78]
Hey!

I'm using custom validation https://valibot.dev/guides/pipelines/#custom-validation in my schemas. which results in that this throws an error.

I need to pass in the `ignoreUnknownValidation` parameter <https://github.com/gcornut/valibot-json-schema?tab=readme-ov-file#ignore-unknown-validation> in order for this to not to throw an error.

Can we make this possible to configure so that it does not throw on unknown validation? 
E.g. adding this as an option parameter when calling createJsonSchemaTransform https://github.com/qlaffont/fastify-type-provider-valibot/blob/bbcdd09d12bb03dbc7ec27c9aea5be0241a96838/src/index.ts#L34

**Comment by qlaffont** [comment]
Yes for sur ! If you want you can make a PR ! (If i have time i will do it)
